### PR TITLE
Modify Spherical Aberration to work via per-sample exposure instead

### PR DESCRIPTION
**Pull request by martymcmodding**
As discussed on Discord recently. 

For the curve itself, I looked at https://jtra.cz/stuff/essays/bokeh/index.html and figured out something that both looks relatively accurate to the plotted graph and results in (imho) pleasing results. Just lerping between radius^4 and 1.0.

https://www.desmos.com/calculator/9oogkblrwx

Something that could be useful is being able to adjust the exponent to produce a harsher or softer ring but I'll leave that up to your preferences.

### CODE REVIEW

**Comment by FransBouma** [comment]
Three images, first is made with the current released code and default boost values, second with your PR code with 0.9 boost (the default) and the third is a downtuned boost with PR code
UE4Game-Win64-Shipping 2023-09-07 15-02-32
UE4Game-Win64-Shipping 2023-09-07 15-08-32
UE4Game-Win64-Shipping 2023-09-07 15-09-57

Your PR works well, with one exception perhaps and that's sharp edges on the shape, as you already commented. I like these a lot (especially also with the fringing due to the current state of the code!) however that's not really doable with what the PR code does. 

This would require an adjustment to the function I recon?

**Comment by FransBouma** [comment]
Another thing I noticed, the center isn't boosted (this is a bug I think that's also present in the release code)
image

**Comment by FransBouma** [comment]
I think changing the formula's '4' value into something like 32 will give very thin edges. Alternatively, if say a factor dictates n rings on the outside are always boosted and the rest, inner rings, are using the spherical aberration formula, this would give the previous results I think? (except the fringing, but let's ignore that for now), but I'm not sure if that messes the overall normalization of the bokeh (I think it does)

**Comment by martymcmodding** [comment]
Spherical aberration is purely radius based, not doing these outlines that you see on polygonal DOF. That's a different effect, however I don't know which one (yet). 

That should be easy to implement though, as my proposed solution allows arbitrary weighting (could even be done in RGB) for each sample. I think both effects should be stacked rather than "inner rings do this, outer rings do that". 

Let me research a bit, I'll update the proposed solution.

**Comment by FransBouma** [comment]
The bicubic catmullrom function isn't used in the shader, so I've removed it. Added a tooltip remark for the fringe so high values could lead to a screen going dark during the first phase of rendering

**Pull request merged**
